# Practicing over Numpy

In [5]:
import numpy as np 
a = np.array(["Waqar","Usama","Asad","Ch.Uzair"])
a 

array(['Waqar', 'Usama', 'Asad', 'Ch.Uzair'], dtype='<U8')

In [6]:
a = np.arange(1, 7)
a

array([1, 2, 3, 4, 5, 6])

In [7]:
b = a[0:] #it will add all the elements present in the list. 
b

array([1, 2, 3, 4, 5, 6])

In [10]:
c = a[4] #indexing 
c

5

In [12]:
np.arange(2,32,2) #it will make an array from 2 to 30 with a difference of 2 between each element.

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [17]:
np.linspace(1, 50, num=10,dtype =np.int64)

array([ 1,  6, 11, 17, 22, 28, 33, 39, 44, 50], dtype=int64)

# 2-D arrays and concatenation 

In [18]:
a = np.array([[1,2,3,4],[4,3,2,1]])
a

array([[1, 2, 3, 4],
       [4, 3, 2, 1]])

In [24]:
b = np.array([[5,6,7,8],[9,8,7,6]])
b

array([[5, 6, 7, 8],
       [9, 8, 7, 6]])

In [25]:
np.concatenate((a,b), axis=0) # dimensions must be same of arrays being concatenated...b

array([[1, 2, 3, 4],
       [4, 3, 2, 1],
       [5, 6, 7, 8],
       [9, 8, 7, 6]])

In [26]:
a.ndim

2

In [28]:
a.size

8

In [29]:
a.shape


(2, 4)

In [30]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])