In [8]:
import numpy as np
a = np.array([1,2,3,4,5])
a
b = np.zeros(3)
b
c = np.ones(2)
c
#creating an empty array of 3 elements
d = np.empty(3)
d

array([0., 0., 0.])

In [9]:
a = np.arange(7)
a

array([0, 1, 2, 3, 4, 5, 6])

In [10]:
b = np.arange(2,10,2)
b

array([2, 4, 6, 8])

In [11]:
c = np.linspace(3,12, num=4)
c

array([ 3.,  6.,  9., 12.])

In [14]:
d = np.ones(4, dtype=np.int16)
d

array([1, 1, 1, 1], dtype=int16)

In [17]:
e = np.ones((7,5))
e

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [24]:
# creating 3-D array 
f = np.arange(24).reshape(2,3,4)
f

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])